// AddRequesForm
export const ADD_PRODUCT_REQUESTED = 'ADD_PRODUCT_REQUESTED';
export const ADD_PRODUCT_DOESNT_EXIST = 'ADD_PRODUCT_DOESNT_EXIST';
export const ADD_PRODUCT_SUCCEDED = 'ADD_PRODUCT_SUCCEDED';

// clients
export const CLIENTS_FETCH_REQUESTED = 'CLIENTS_FETCH_REQUESTED';
export const CLIENTS_FETCHED = 'CLIENTS_FETCHED';
