// AddRequesForm
export const ADD_PRODUCT_REQUESTED = 'ADD_PRODUCT_REQUESTED';
export const ADD_PRODUCT_DOESNT_EXIST = 'ADD_PRODUCT_DOESNT_EXIST';
export const ADD_PRODUCT_SUCCEDED = 'ADD_PRODUCT_SUCCEDED';
