// AddRequesForm
export const ADD_PRODUCT_REQUESTED = 'ADD_PRODUCT_REQUESTED';
export const ADD_PRODUCT_ALREADY_EXISTS = 'ADD_PRODUCT_ALREADY_EXISTS';
export const ADD_PRODUCT_DOESNT_EXIST = 'ADD_PRODUCT_DOESNT_EXIST';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';
export const ADD_PRODUCT_SUCCEDED = 'ADD_PRODUCT_SUCCEDED';
